### ISSUE TITLE
Android Demo

### ISSUE THREAD

**Issue by pixelbendr** [VirgilSecurity/virgil#2]
Please can we have a simple Java Android demo, I can't seem to figure out where to initialise the library. A simple demo for code organisation purposes would be create. Same goes for Swift and Objective C on iOS

**Comment by pixelbendr** [comment]
Any info on this?

**Comment by ddain** [comment]
Hey there, 

We are sending you links to what you've asked for through @support.
Please stand by (and you can close this issue since we got ticket open for you in our support system).
