### ISSUE TITLE
No implementation found for void com.virgilsecurity.crypto.virgil_crypto_javaJNI.swig_module_init()

### ISSUE THREAD

**Issue by pixelbendr** [VirgilSecurity/virgil#3]
I keep getting this error when trying to initialise virgil. " java.lang.UnsatisfiedLinkError: No implementation found for void com.virgilsecurity.crypto.virgil_crypto_javaJNI.swig_module_init() (tried Java_com_virgilsecurity_crypto_virgil_1crypto_1javaJNI_swig_1module_1init and Java_com_virgilsecurity_crypto_virgil_1crypto_1javaJNI_swig_1module_1init__) "

**Comment by nau11713** [comment]
if the mistake still is available, please write about it here - https://github.com/VirgilSecurity/virgil-sdk-java-android
